feat: PreflightWorkflow
pexip/pexip-android-sdk pull request #34
Opened 2022-10-05 11:06 UTC by drymarau

This PR introduces a new start destination in navigation graph - preflight.

It somewhat follows the existing UX of Pexip Infinity Connect apps and will enable call transfer handling in the near future.

2022-10-06 08:53 UTC, tpettersen requested changes
The UI looks sharp 👍 Found a couple of issues

2022-10-06 08:53 UTC, tpettersen commented on sample/src/main/kotlin/com/pexip/sdk/sample/preflight/PreflightScreen.kt
> +    }
It is somewhat annoying that I lose state pressing outside the popups by accident. E.g: I introduce myself, write the meeting uri + host and the touches the screen outside of the popup when pin challenge is presented. Then I have to start all over again. That is a bit unfortunate

2022-10-06 08:53 UTC, tpettersen commented on sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
> +    private fun RenderContext.cameraVideoTrackSideEffect(track: CameraVideoTrack?) {
There is a lifecycle issue with the camera:
- Open preflight
- Put the app in the background
- Open the camera app on your phone
- Open Video SDK app again

The camera is now gone, and you will not get it back when entering a conference even. The app needs to restart to get back to normal.

2022-10-07 12:49 UTC, tpettersen commented on sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
> +        if (count > 0u) runningSideEffect("createCameraVideoTrackSideEffect($count)") {
This _works_, but I must admit that I am not to fan of counters here. 😅 

Just to have the discussion, what if you added `onCameraConnected(deviceName: String)` in `CameraVideoTrack.Callback`. Then you could store that deviceName in the state. 

`OnCameraDisconnected` sets the track to null, but you would still have the `deviceName`. So using `createCameraVideoTrack(deviceName, callback)` when the app is in the background would throw `IllegalStateException` if it is not available, and would not produce more renderings. The next time the app opens again, this should now work

2022-10-07 12:55 UTC, drymarau commented on sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
> +        if (count > 0u) runningSideEffect("createCameraVideoTrackSideEffect($count)") {
I don't think it's a good approach as the `deviceName` may not necessarily be static and overall feels way more complex to track application lifecycle.

2022-10-07 13:20 UTC, drymarau commented on sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
> +        if (count > 0u) runningSideEffect("createCameraVideoTrackSideEffect($count)") {
> Huh, could the device name of the current camera actually change runtime? 🤔

If it's an external camera it's definitely possible, there are no guarantees about `deviceName` not changing.

Use cases differ and I don't think it's feasible to provide Android lifecycle integration at all - it's fairly easy, if required, to build one yourself.

2022-10-07 13:22 UTC, drymarau commented on sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
> +        if (count > 0u) runningSideEffect("createCameraVideoTrackSideEffect($count)") {
As for in-call, general advice is to not open camera app while in a conference call.

2022-10-07 13:51 UTC, tpettersen commented on sample/src/main/kotlin/com/pexip/sdk/sample/SampleWorkflow.kt
> +        if (count > 0u) runningSideEffect("createCameraVideoTrackSideEffect($count)") {
ok 👌

2022-10-07 14:23 UTC, merged