feat(media): handle coroutines exceptions
pexip/pexip-android-sdk pull request #432
Opened 2024-06-12 11:50 UTC by tpettersen

This stops the exceptions from API calls during a media connection propagating uncontrollably to the clients and crashing them

2024-06-12 13:20 UTC, drymarau requested changes

2024-06-12 13:20 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
> +        }
I believe this is unnecessary since `CancellationException` will be ignored anyway. A debug/verbose log entry would be nice to have though, even if for a short period of time.

2024-06-12 13:20 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
> +            context = SupervisorJob(job) + workerDispatcher,
I'd suggest we treat other places where `CoroutineScope` is invoked in the same manner.

2024-06-12 13:41 UTC, tpettersen commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
> +            context = SupervisorJob(job) + workerDispatcher,
In this PR?

2024-06-13 10:12 UTC, tpettersen commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
> +            context = SupervisorJob(job) + workerDispatcher,
*bump*

2024-06-13 10:31 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/WebRtcMediaConnectionFactory.kt
> +            context = SupervisorJob(job) + workerDispatcher,
yup

2024-06-14 09:04 UTC, drymarau requested changes

2024-06-14 09:04 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcVideoTrack.kt
> +    context: CoroutineContext,
Just to be safe, this should still use the `CoroutineScope` passed down by the parent (if there's any) - there's no `close()`/`dispose()` here, so it will remain active.

2024-06-14 09:04 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcMediaConnection.kt
> +        .map { track -> track?.let { WebRtcVideoTrack(it, this.coroutineContext) } }
Should be this class' scope, not `coroutineContext`.

2024-06-18 09:18 UTC, drymarau requested changes

2024-06-18 09:18 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    private val scope: CoroutineScope = CoroutineScope(coroutineContext),
Primary constructor should stay the same. Add a secondary constructor that accepts `CoroutineContext` instead of `CoroutineScope` and creates a new `CoroutineScope` using it. This will apply to pretty much every class that changed in this PR (apart from a few obvious ones).

2024-06-21 07:51 UTC, drymarau requested changes

2024-06-21 07:51 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcLocalVideoTrack.kt
> +    private val scope: CoroutineScope,
Should stay `protected`.

2024-06-21 07:51 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    private val scope: CoroutineScope,
Doesn't need `private val` after changes to `WebRtcLocalVideoTrack`.

2024-06-21 07:51 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
A bit weird formatting on `ktlint` part, could we switch `CameraVideoTrack` and `WebRtcLocalVideoTrack` here?

```kotlin
) : CameraVideoTrack,
    WebRtcLocalVideoTrack(
        applicationContext = applicationContext,
        eglBase = eglBase,
        scope = scope,
        videoCapturer = videoCapturer,
        videoSource = videoSource,
        videoTrack = videoTrack,
        signalingDispatcher = signalingDispatcher,
    ) {
```

2024-06-21 07:53 UTC, tpettersen commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
I totally agree, but this did not: https://github.com/pexip/pexip-android-sdk/actions/runs/9593741949/job/26454833027

2024-06-21 08:09 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
`WebRtcLocalVideoTrack` should be put on a newline (it was on the same line in the run you linked). Seems to pass locally for me.

2024-06-21 08:15 UTC, tpettersen commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
https://github.com/pexip/pexip-android-sdk/actions/runs/9610456601/job/26506978811?pr=432 😭

2024-06-21 08:40 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
🤦

2024-06-21 08:43 UTC, tpettersen commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
Got any other ideas, or should I just go with the flow?

2024-06-21 10:47 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
Sadly, no. Just revert [6a38876](https://github.com/pexip/pexip-android-sdk/pull/432/commits/6a38876d768cfa87f9932484cc678f9de2616c48) then.

2024-06-21 10:48 UTC, drymarau commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
But do retain `protected` changes 🙈

2024-06-21 10:49 UTC, tpettersen commented on sdk-media-webrtc/src/main/kotlin/com/pexip/sdk/media/webrtc/internal/WebRtcCameraVideoTrack.kt
> +    CameraVideoTrack {
Done ;)

2024-06-21 10:54 UTC, drymarau approved these changes

2024-06-21 11:02 UTC, merged