fix: insert black frame when VideoCapturer stops
pexip/pexip-android-sdk pull request #86
Opened 2023-04-06 14:13 UTC by drymarau

When a client stops capturing, last sent frame will be left lingering in
the conference. While this is not an issue if this change is signalled
via REST API, it affects users in gateway calls where removing from mix
is not supported.

This commit inserts a black frame when `onCapturerStopped()` in invoked.

2023-04-11 12:11 UTC, vadymmarkov commented
In the Swift SDK we render empty frame when video capturer stops by calling `renderFrame(nil)` on `RTCVideoRenderer`, which I believe does the same thing. But I guess you don't have `RTCVideoRenderer` on Android.

2023-04-11 12:15 UTC, drymarau commented
Does it affect the remote end as well or just the local?

2023-04-11 12:40 UTC, vadymmarkov commented
You're right, I misread the issue. It affects just the local. 
But shouldn't it be enough to set `isEnabled` to false on `RTCVideoTrack` before you stop video capturer?

2023-04-11 13:27 UTC, drymarau commented
@tpettersen, I'm able to reproduce this issue. Can you check if passing `width` and `height` directly instead of frame calculation works?

2023-04-11 13:29 UTC, tpettersen commented
I figured out that there is something off when creating the black buffer. If I change the code to do this `val buffer = createBlackBuffer(width, height)` it works.

2023-04-11 13:29 UTC, tpettersen commented
> @tpettersen, I'm able to reproduce this issue. Can you check if passing `width` and `height` directly instead of frame calculation works?

..yeah 😅 you beat me to it with seconds

2023-04-11 13:33 UTC, drymarau commented
> I figured out that there is something off when creating the black buffer. If I change the code to do this `val buffer = createBlackBuffer(width, height)` it works.

It appears that resulting frame's size when it's derived from `Rational` is not very welcome by the encoder, hence the crash.

I've tried to pass a 256x144 frame and it works on S23. Maybe something static like 640x480 would do the trick without keeping aspect ratio.

2023-04-11 16:17 UTC, vadymmarkov commented
> I tried that approach but couldn't get it to work reliably - it appears at least one frame has to be sent after the track has been disabled for remote end to see the black frame.

On iOS we add a small delay between disabling the track and stopping the capturer, which is arguably not the best way to solve this, but proved to be working in our apps. 

There is also the case when the app crashes during the call or is closed by user, which would cause the same problem. But I don't think there is anything we can do about it on the client.

2023-04-12 06:48 UTC, tpettersen requested changes
This does not work for me I am afraid. The frame is still lingering. I think you need to allocate a buffer with the correct size and a frame with the correct rotation. 

When testing I pass width/height for my device and it works as intended in landscape only. If I also set the correct rotation it works both portrait and landscape. 

```
val buffer = createBlackBuffer(width, height)
val frame = VideoFrame(buffer, rotation, 0)
```

2023-04-12 08:23 UTC, drymarau commented
> When testing I pass width/height for my device and it works as intended in landscape only. If I also set the correct rotation it works both portrait and landscape.

Doesn't work for me reliably - frames with `rotation=0` stay while `rotation=180` are replaced with a black one as expected.

2023-04-12 08:35 UTC, tpettersen commented
> > When testing I pass width/height for my device and it works as intended in landscape only. If I also set the correct rotation it works both portrait and landscape.
> 
> Doesn't work for me reliably - frames with `rotation=0` stay while `rotation=180` are replaced with a black one as expected.

True. Works for me with `180` and `270`, but not `0` 🤔

2023-04-12 08:46 UTC, drymarau commented
> True. Works for me with `180` and `270`, but not `0` 🤔

So sending at least 2 frames with correctly set `timestampNs` regardless of frame size and rotation seems to work, though I need to verify it for other codecs.

2023-04-12 16:38 UTC, drymarau commented
Guess I'll bump it to 4 frames 🙂

2023-04-13 08:06 UTC, merged